# -*- encoding: utf-8 -*-

=begin
#Seller API

#This API reference documents endpoints that are exclusive to sellers.

The version of the OpenAPI document: v2021-01-01
Contact: support@convictional.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0-SNAPSHOT

=end

$:.push File.expand_path("../lib", __FILE__)
require "convictional_seller/version"

Gem::Specification.new do |s|
  s.name        = "convictional_seller"
  s.version     = ConvictionalSeller::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = ["support@convictional.com"]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "Seller API Ruby Gem"
  s.description = "This API reference documents endpoints that are exclusive to sellers."
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'faraday', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
