=begin
#Seller API

#This API reference documents endpoints that are exclusive to sellers.

The version of the OpenAPI document: v2021-01-01
Contact: support@convictional.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ConvictionalSeller::PriceListApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PriceListApi' do
  before do
    # run before each test
    @api_instance = ConvictionalSeller::PriceListApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PriceListApi' do
    it 'should create an instance of PriceListApi' do
      expect(@api_instance).to be_instance_of(ConvictionalSeller::PriceListApi)
    end
  end

  # unit tests for delete_price_list_by_id
  # Delete price list
  # An endpoint for permanently deleting price lists.
  # @param price_id ID of the price list
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2001]
  describe 'delete_price_list_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_price_list_by_id
  # Get price list
  # An endpoint for retrieving price lists. In cases where a price list may contain invalid SKUs, those SKUs are not included in the response.
  # @param price_id ID of the price list
  # @param [Hash] opts the optional parameters
  # @return [Price]
  describe 'get_price_list_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_price_list_template
  # Get price list template
  # Returns a CSV template that can be filled with retail and base prices for all variants and then upload it to /prices/upload
  # @param authorization Auth token provided by Convictional upon account creation.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_price_list_template test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_price_list
  # Create price list
  # An endpoint to create a price list for the given company API key
  # @param price All the fields in a pricelist
  # @param [Hash] opts the optional parameters
  # @return [Price]
  describe 'post_price_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_price_list_csv
  # Upload price list
  # An endpoint for creating new price lists using a CSV file.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name The name of the new price list.
  # @option opts [Array<Object>] :file A CSV file containing price list information. The following fields represent the columns in the CSV file. All columns must be present in the given order and the first row of each column must contain the exact header from below. The columns marked as read only must still be included in requests, but can be blank except for the header.
  # @return [InlineResponse2002]
  describe 'post_price_list_csv test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_price_list_by_id
  # Update price list
  # An endpoint for fully updating price lists.
  # @param price_id ID of the price list
  # @param [Hash] opts the optional parameters
  # @option opts [PriceUpdate] :price_update 
  # @return [Price]
  describe 'put_price_list_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
