=begin
#Seller API

#This API reference documents endpoints that are exclusive to sellers.

The version of the OpenAPI document: v2021-01-01
Contact: support@convictional.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ConvictionalSeller::VariantApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VariantApi' do
  before do
    # run before each test
    @api_instance = ConvictionalSeller::VariantApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VariantApi' do
    it 'should create an instance of VariantApi' do
      expect(@api_instance).to be_instance_of(ConvictionalSeller::VariantApi)
    end
  end

  # unit tests for patch_variant_by_id
  # Update variant
  # An endpoint for partially updating a product variant with the provided ID
  # @param product_id ID of the product to update
  # @param variant_id ID of the variant to update
  # @param patch_variant 
  # @param [Hash] opts the optional parameters
  # @return [Variant]
  describe 'patch_variant_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
