=begin
#Seller API

#This API reference documents endpoints that are exclusive to sellers.

The version of the OpenAPI document: v2021-01-01
Contact: support@convictional.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ConvictionalSeller::InlineResponse2003
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ConvictionalSeller::InlineResponse2003 do
  let(:instance) { ConvictionalSeller::InlineResponse2003.new }

  describe 'test an instance of InlineResponse2003' do
    it 'should create an instance of InlineResponse2003' do
      expect(instance).to be_instance_of(ConvictionalSeller::InlineResponse2003)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
