=begin
#Seller API

#This API reference documents endpoints that are exclusive to sellers.

The version of the OpenAPI document: v2021-01-01
Contact: support@convictional.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0-SNAPSHOT

=end

# Common files
require 'convictional_seller/api_client'
require 'convictional_seller/api_error'
require 'convictional_seller/version'
require 'convictional_seller/configuration'

# Models
require 'convictional_seller/models/address'
require 'convictional_seller/models/dimensions'
require 'convictional_seller/models/empty_error'
require 'convictional_seller/models/error_message'
require 'convictional_seller/models/google_product_category'
require 'convictional_seller/models/image'
require 'convictional_seller/models/inline_response200'
require 'convictional_seller/models/inline_response2001'
require 'convictional_seller/models/inline_response2002'
require 'convictional_seller/models/inline_response2003'
require 'convictional_seller/models/inline_response400'
require 'convictional_seller/models/inline_response4001'
require 'convictional_seller/models/inline_response401'
require 'convictional_seller/models/inline_response404'
require 'convictional_seller/models/inline_response415'
require 'convictional_seller/models/inline_response500'
require 'convictional_seller/models/invoice'
require 'convictional_seller/models/order'
require 'convictional_seller/models/order_cancellation'
require 'convictional_seller/models/order_fulfillment'
require 'convictional_seller/models/order_fulfillment_items'
require 'convictional_seller/models/order_item'
require 'convictional_seller/models/order_item_cancellation'
require 'convictional_seller/models/order_update'
require 'convictional_seller/models/patch_image'
require 'convictional_seller/models/patch_option'
require 'convictional_seller/models/patch_product'
require 'convictional_seller/models/patch_variant'
require 'convictional_seller/models/patch_variant_images'
require 'convictional_seller/models/price'
require 'convictional_seller/models/price_list'
require 'convictional_seller/models/price_update'
require 'convictional_seller/models/price_update_list'
require 'convictional_seller/models/product'
require 'convictional_seller/models/product_options'
require 'convictional_seller/models/response_meta_data'
require 'convictional_seller/models/seller_invoice_item'
require 'convictional_seller/models/seller_invoice_response'
require 'convictional_seller/models/seller_order_invoice_tax'
require 'convictional_seller/models/seller_order_refund'
require 'convictional_seller/models/seller_order_refund_item'
require 'convictional_seller/models/seller_tax'
require 'convictional_seller/models/variant'
require 'convictional_seller/models/variant_images'

# APIs
require 'convictional_seller/api/order_api'
require 'convictional_seller/api/price_list_api'
require 'convictional_seller/api/product_api'
require 'convictional_seller/api/variant_api'

module ConvictionalSeller
  class << self
    # Customize default settings for the SDK using block.
    #   ConvictionalSeller.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
